// This file is auto-generated by @hey-api/openapi-ts

/**
 * AdminStatsResponse
 */
export type AdminStatsResponse = {
    /**
     * Total Posts
     */
    total_posts: number;
    /**
     * Published Posts
     */
    published_posts: number;
    /**
     * Draft Posts
     */
    draft_posts: number;
    /**
     * Featured Posts
     */
    featured_posts: number;
    /**
     * Total Views
     */
    total_views: number;
    /**
     * Total Comments
     */
    total_comments: number;
    /**
     * Comments In Period
     */
    comments_in_period: number;
    /**
     * Comments Prev Period
     */
    comments_prev_period: number;
    /**
     * Avg Read Time Minutes
     */
    avg_read_time_minutes: number;
    /**
     * Top Posts
     */
    top_posts: Array<TopPostStat>;
    /**
     * Comments By Day
     */
    comments_by_day: Array<DailyCount>;
    /**
     * Period
     */
    period?: string | null;
};

/**
 * AvatarUpdate
 */
export type AvatarUpdate = {
    /**
     * Avatar Url
     */
    avatar_url: string | null;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CommentAuthor
 */
export type CommentAuthor = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Body
     */
    body: string;
};

/**
 * CommentResponse
 */
export type CommentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Post Id
     */
    post_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Body
     */
    body: string;
    /**
     * Created At
     */
    created_at: string;
    author: CommentAuthor;
    /**
     * Likes Count
     */
    likes_count?: number;
    /**
     * User Liked
     */
    user_liked?: boolean;
    /**
     * Replies
     */
    replies?: Array<CommentResponse>;
};

/**
 * ContactRequest
 */
export type ContactRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
    /**
     * Captcha Token
     */
    captcha_token: string;
};

/**
 * DailyCount
 */
export type DailyCount = {
    /**
     * Date
     */
    date: string;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PaginatedPostsResponse
 */
export type PaginatedPostsResponse = {
    /**
     * Posts
     */
    posts: Array<PostResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * PostAuthorResponse
 */
export type PostAuthorResponse = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * PostCreate
 */
export type PostCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Excerpt
     */
    excerpt: string;
    /**
     * Content
     */
    content: string;
    status?: PostStatus;
    /**
     * Featured
     */
    featured?: boolean;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
    /**
     * Meta Title
     */
    meta_title?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
    /**
     * Tag Names
     */
    tag_names?: Array<string>;
};

/**
 * PostResponse
 */
export type PostResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Excerpt
     */
    excerpt: string;
    status: PostStatus;
    /**
     * Featured
     */
    featured: boolean;
    /**
     * Cover Image Url
     */
    cover_image_url: string | null;
    /**
     * Meta Title
     */
    meta_title: string | null;
    /**
     * Meta Description
     */
    meta_description: string | null;
    /**
     * View Count
     */
    view_count: number;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Tags
     */
    tags?: Array<TagResponse>;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Read Time
     */
    read_time?: string;
    author?: PostAuthorResponse | null;
};

/**
 * PostStatus
 */
export type PostStatus = 'draft' | 'published';

/**
 * PostUpdate
 */
export type PostUpdate = {
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Excerpt
     */
    excerpt?: string | null;
    /**
     * Content
     */
    content?: string | null;
    status?: PostStatus | null;
    /**
     * Featured
     */
    featured?: boolean | null;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
    /**
     * Meta Title
     */
    meta_title?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
    /**
     * Tag Names
     */
    tag_names?: Array<string> | null;
};

/**
 * PresignRequest
 */
export type PresignRequest = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
};

/**
 * PresignResponse
 */
export type PresignResponse = {
    /**
     * Url
     */
    url: string;
    /**
     * Fields
     */
    fields: {
        [key: string]: string;
    };
    /**
     * Public Url
     */
    public_url: string;
    /**
     * Key
     */
    key: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Stack
     */
    stack?: Array<string>;
    status?: ProjectStatus;
    /**
     * Stars
     */
    stars?: number;
    /**
     * Forks
     */
    forks?: number;
    /**
     * Github Url
     */
    github_url?: string | null;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Accent
     */
    accent?: string;
    /**
     * Category
     */
    category: string;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Stack
     */
    stack: Array<string>;
    status: ProjectStatus;
    /**
     * Stars
     */
    stars: number;
    /**
     * Forks
     */
    forks: number;
    /**
     * Github Url
     */
    github_url: string | null;
    /**
     * Live Url
     */
    live_url: string | null;
    /**
     * Accent
     */
    accent: string;
    /**
     * Category
     */
    category: string;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectStatus
 */
export type ProjectStatus = 'completed' | 'in_progress' | 'archived';

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Stack
     */
    stack?: Array<string> | null;
    status?: ProjectStatus | null;
    /**
     * Stars
     */
    stars?: number | null;
    /**
     * Forks
     */
    forks?: number | null;
    /**
     * Github Url
     */
    github_url?: string | null;
    /**
     * Live Url
     */
    live_url?: string | null;
    /**
     * Accent
     */
    accent?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number | null;
};

/**
 * TagCreate
 */
export type TagCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color?: string;
};

/**
 * TagResponse
 */
export type TagResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color: string;
};

/**
 * TagWithCountResponse
 */
export type TagWithCountResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Color
     */
    color: string;
    /**
     * Post Count
     */
    post_count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TopPostStat
 */
export type TopPostStat = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * View Count
     */
    view_count: number;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersUpdateAvatarMeData = {
    body: AvatarUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/avatar';
};

export type UsersUpdateAvatarMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateAvatarMeError = UsersUpdateAvatarMeErrors[keyof UsersUpdateAvatarMeErrors];

export type UsersUpdateAvatarMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateAvatarMeResponse = UsersUpdateAvatarMeResponses[keyof UsersUpdateAvatarMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type PostsReadPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Page
         */
        page?: number;
    };
    url: '/api/v1/posts';
};

export type PostsReadPostsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsReadPostsError = PostsReadPostsErrors[keyof PostsReadPostsErrors];

export type PostsReadPostsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedPostsResponse;
};

export type PostsReadPostsResponse = PostsReadPostsResponses[keyof PostsReadPostsResponses];

export type PostsCreatePostData = {
    body: PostCreate;
    path?: never;
    query?: never;
    url: '/api/v1/posts';
};

export type PostsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsCreatePostError = PostsCreatePostErrors[keyof PostsCreatePostErrors];

export type PostsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type PostsCreatePostResponse = PostsCreatePostResponses[keyof PostsCreatePostResponses];

export type PostsReadAllPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Status
         */
        status?: PostStatus | null;
        /**
         * Page
         */
        page?: number;
    };
    url: '/api/v1/posts/admin/all';
};

export type PostsReadAllPostsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsReadAllPostsError = PostsReadAllPostsErrors[keyof PostsReadAllPostsErrors];

export type PostsReadAllPostsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedPostsResponse;
};

export type PostsReadAllPostsResponse = PostsReadAllPostsResponses[keyof PostsReadAllPostsResponses];

export type PostsReadPostData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/{slug}';
};

export type PostsReadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsReadPostError = PostsReadPostErrors[keyof PostsReadPostErrors];

export type PostsReadPostResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type PostsReadPostResponse = PostsReadPostResponses[keyof PostsReadPostResponses];

export type PostsDeletePostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/posts/{post_id}';
};

export type PostsDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsDeletePostError = PostsDeletePostErrors[keyof PostsDeletePostErrors];

export type PostsDeletePostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostsDeletePostResponse = PostsDeletePostResponses[keyof PostsDeletePostResponses];

export type PostsUpdatePostData = {
    body: PostUpdate;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/posts/{post_id}';
};

export type PostsUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsUpdatePostError = PostsUpdatePostErrors[keyof PostsUpdatePostErrors];

export type PostsUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type PostsUpdatePostResponse = PostsUpdatePostResponses[keyof PostsUpdatePostResponses];

export type PostsPublishPostData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/posts/{post_id}/publish';
};

export type PostsPublishPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostsPublishPostError = PostsPublishPostErrors[keyof PostsPublishPostErrors];

export type PostsPublishPostResponses = {
    /**
     * Successful Response
     */
    200: PostResponse;
};

export type PostsPublishPostResponse = PostsPublishPostResponses[keyof PostsPublishPostResponses];

export type UploadsGetCoverImageUploadUrlData = {
    body: PresignRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uploads/cover-image-url';
};

export type UploadsGetCoverImageUploadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadsGetCoverImageUploadUrlError = UploadsGetCoverImageUploadUrlErrors[keyof UploadsGetCoverImageUploadUrlErrors];

export type UploadsGetCoverImageUploadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignResponse;
};

export type UploadsGetCoverImageUploadUrlResponse = UploadsGetCoverImageUploadUrlResponses[keyof UploadsGetCoverImageUploadUrlResponses];

export type UploadsGetAvatarUploadUrlData = {
    body: PresignRequest;
    path?: never;
    query?: never;
    url: '/api/v1/uploads/avatar-url';
};

export type UploadsGetAvatarUploadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadsGetAvatarUploadUrlError = UploadsGetAvatarUploadUrlErrors[keyof UploadsGetAvatarUploadUrlErrors];

export type UploadsGetAvatarUploadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignResponse;
};

export type UploadsGetAvatarUploadUrlResponse = UploadsGetAvatarUploadUrlResponses[keyof UploadsGetAvatarUploadUrlResponses];

export type TagsGetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tags';
};

export type TagsGetTagsResponses = {
    /**
     * Response Tags-Gettags
     * Successful Response
     */
    200: Array<TagWithCountResponse>;
};

export type TagsGetTagsResponse = TagsGetTagsResponses[keyof TagsGetTagsResponses];

export type TagsCreateTagData = {
    body: TagCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tags';
};

export type TagsCreateTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TagsCreateTagError = TagsCreateTagErrors[keyof TagsCreateTagErrors];

export type TagsCreateTagResponses = {
    /**
     * Successful Response
     */
    200: TagWithCountResponse;
};

export type TagsCreateTagResponse = TagsCreateTagResponses[keyof TagsCreateTagResponses];

export type TagsDeleteTagData = {
    body?: never;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}';
};

export type TagsDeleteTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TagsDeleteTagError = TagsDeleteTagErrors[keyof TagsDeleteTagErrors];

export type TagsDeleteTagResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type TagsDeleteTagResponse = TagsDeleteTagResponses[keyof TagsDeleteTagResponses];

export type ProjectsGetProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type ProjectsGetProjectsResponses = {
    /**
     * Response Projects-Get Projects
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type ProjectsGetProjectsResponse = ProjectsGetProjectsResponses[keyof ProjectsGetProjectsResponses];

export type ProjectsCreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type ProjectsCreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectsCreateProjectError = ProjectsCreateProjectErrors[keyof ProjectsCreateProjectErrors];

export type ProjectsCreateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type ProjectsCreateProjectResponse = ProjectsCreateProjectResponses[keyof ProjectsCreateProjectResponses];

export type ProjectsDeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ProjectsDeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectsDeleteProjectError = ProjectsDeleteProjectErrors[keyof ProjectsDeleteProjectErrors];

export type ProjectsDeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectsDeleteProjectResponse = ProjectsDeleteProjectResponses[keyof ProjectsDeleteProjectResponses];

export type ProjectsUpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ProjectsUpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectsUpdateProjectError = ProjectsUpdateProjectErrors[keyof ProjectsUpdateProjectErrors];

export type ProjectsUpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type ProjectsUpdateProjectResponse = ProjectsUpdateProjectResponses[keyof ProjectsUpdateProjectResponses];

export type CommentsGetPostCommentsData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/posts/{post_id}/comments';
};

export type CommentsGetPostCommentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommentsGetPostCommentsError = CommentsGetPostCommentsErrors[keyof CommentsGetPostCommentsErrors];

export type CommentsGetPostCommentsResponses = {
    /**
     * Response Comments-Get Post Comments
     * Successful Response
     */
    200: Array<CommentResponse>;
};

export type CommentsGetPostCommentsResponse = CommentsGetPostCommentsResponses[keyof CommentsGetPostCommentsResponses];

export type CommentsCreateCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Post Id
         */
        post_id: string;
    };
    query?: never;
    url: '/api/v1/posts/{post_id}/comments';
};

export type CommentsCreateCommentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommentsCreateCommentError = CommentsCreateCommentErrors[keyof CommentsCreateCommentErrors];

export type CommentsCreateCommentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CommentsCreateCommentResponse = CommentsCreateCommentResponses[keyof CommentsCreateCommentResponses];

export type CommentsReplyToCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/comments/{id}/replies';
};

export type CommentsReplyToCommentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommentsReplyToCommentError = CommentsReplyToCommentErrors[keyof CommentsReplyToCommentErrors];

export type CommentsReplyToCommentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CommentsReplyToCommentResponse = CommentsReplyToCommentResponses[keyof CommentsReplyToCommentResponses];

export type CommentsToggleCommentLikeData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/comments/{id}/like';
};

export type CommentsToggleCommentLikeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommentsToggleCommentLikeError = CommentsToggleCommentLikeErrors[keyof CommentsToggleCommentLikeErrors];

export type CommentsToggleCommentLikeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CommentsToggleCommentLikeResponse = CommentsToggleCommentLikeResponses[keyof CommentsToggleCommentLikeResponses];

export type CommentsDeleteCommentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/comments/{id}';
};

export type CommentsDeleteCommentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommentsDeleteCommentError = CommentsDeleteCommentErrors[keyof CommentsDeleteCommentErrors];

export type CommentsDeleteCommentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CommentsDeleteCommentResponse = CommentsDeleteCommentResponses[keyof CommentsDeleteCommentResponses];

export type ContactSubmitContactFormData = {
    body: ContactRequest;
    path?: never;
    query?: never;
    url: '/api/v1/contact';
};

export type ContactSubmitContactFormErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContactSubmitContactFormError = ContactSubmitContactFormErrors[keyof ContactSubmitContactFormErrors];

export type ContactSubmitContactFormResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AdminGetAdminStatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Period
         */
        period?: ('7d' | '30d' | '90d' | '12mo') | null;
    };
    url: '/api/v1/admin/stats';
};

export type AdminGetAdminStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminGetAdminStatsError = AdminGetAdminStatsErrors[keyof AdminGetAdminStatsErrors];

export type AdminGetAdminStatsResponses = {
    /**
     * Successful Response
     */
    200: AdminStatsResponse;
};

export type AdminGetAdminStatsResponse = AdminGetAdminStatsResponses[keyof AdminGetAdminStatsResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};